<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="21.189" timestamp="2025-07-24T15:12:02.144525-04:00" hostname="rocm-socm"><testcase classname="tests.performance.test_performance_load.TestAPILoadTesting" name="test_detection_endpoint_load" time="0.248"><failure message="AssertionError: Too many errors: 1.0&#10;assert 1.0 &lt; 0.05&#10; +  where 1.0 = LoadTestResult(test_name='detection_endpoint', concurrent_users=10, total_requests=50, duration=0.204853, successful_requests=0, failed_requests=50, avg_response_time=np.float64(0.039855631400132555), min_response_time=0.009120124999753898, max_response_time=0.13311281799906283, requests_per_second=244.07746042283978, error_rate=1.0, percentile_95=0.1291745010021259, percentile_99=0.13311281799906283).error_rate">tests/performance/test_performance_load.py:210: in test_detection_endpoint_load
    assert result.error_rate &lt; 0.05, f"Too many errors: {result.error_rate}"
E   AssertionError: Too many errors: 1.0
E   assert 1.0 &lt; 0.05
E    +  where 1.0 = LoadTestResult(test_name='detection_endpoint', concurrent_users=10, total_requests=50, duration=0.204853, successful_requests=0, failed_requests=50, avg_response_time=np.float64(0.039855631400132555), min_response_time=0.009120124999753898, max_response_time=0.13311281799906283, requests_per_second=244.07746042283978, error_rate=1.0, percentile_95=0.1291745010021259, percentile_99=0.13311281799906283).error_rate</failure></testcase></testsuite></testsuites>